version: "1.0"
info:
  model: int-scaffold
packages:
- name: EdgeNL_MIHE_BNLXDemo
  gitServerName: NL_MIHE_Github
  gitUrl: https://github.com/elpinjo/EdgeNL_MIHE_BNLXDemo
  gitUsername: elpinjo
  gitToken: edge.scaffolding.EdgeNL_MIHE_BNLXDemo.NL_MIHE_Github.gitToken
  gitBranch: main
